# Generated by Django 5.2.5 on 2025-08-21 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('nomeSetor', models.CharField(max_length=200)),
                ('dataCadastro', models.DateField()),
                ('prioridade', models.CharField(choices=[('BAIXA', 'BAIXA'), ('MEDIA', 'MEDIA'), ('ALTA', 'ALTA')])),
                ('status', models.CharField(choices=[('A FAZER', 'A FAZER'), ('FAZENDO', 'FAZENDO'), ('FEITO', 'FEITO')])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
    ]
