# Generated by Django 5.2.5 on 2025-09-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('A FAZER', 'A FAZER'), ('FAZENDO', 'FAZENDO'), ('FEITO', 'FEITO')], default='A FAZER'),
        ),
    ]
